### ISSUE TITLE
support for cats-effect 3.x

### ISSUE THREAD

**Issue by yanns** [djspiewak/cats-effect-testing#117]
cats-effect 3.x is coming.
This library would need some changes to support it.
For example: https://github.com/http4s/http4s/blob/52caa170f4c4859050f7876492a112c6f40c2856/testing/src/main/scala/org/http4s/testing/CatsEffect.scala

I don't know if there is a plan how to move to cats-effect 3.x.
I'd be happy to contribute those changes.
Should I open a PR?

**Comment by djspiewak** [comment]
I'm almost done with the changes actually! I got hung up by minitest. I'll see if I can bring it over the finish line.

**Comment by djspiewak** [comment]
Oh, forgot to close this. `1.0-23-f76ace5` has been released with CE3 support. I'll do a proper milestone release once the dust settles, as well as add some other nice things like ScalaJS support.
