### ISSUE TITLE
`libraryDependencies` link is broken

### ISSUE THREAD

**Issue by kell18** [djspiewak/cats-effect-testing#156]
Hi! 

There is no `"org.typelevel" %% "cats-effect-testing-specs2" % "<version>"` but there is  `"com.codecommit" %% "cats-effect-testing-specs2" % "<version>"` (com.codecommit instead of org.typelevel)

**Comment by LLCampos** [comment]
Versions `1.*` seem to be available at `"org.typelevel"`, `0.*` on `"com.codecommit"`.

**Comment by djspiewak** [comment]
Yeah the documentation needs to be updated to note that. Good call out!

**Comment by rossabaker** [comment]
Fixed in aa3a3fc
