### ISSUE TITLE
utest assert macro package clash

### ISSUE THREAD

**Issue by Slakah** [djspiewak/cats-effect-testing#16]
Hi folks! Thanks for the great library.

This issue isn't strictly speaking an issue in cats-effect-testing, but I believe to be an issue with utest. Raising this issue here, just incase anyone else encounters this problem. 

Noticed a small ergonomic issue with the current package naming, basically when you do `import cats.effect._`, the `utest` package is brought into scope. The assert macro references [`utest.asserts.Asserts.assertImpl`](https://github.com/lihaoyi/utest/blob/master/utest/src/utest/asserts/Asserts.scala#L99) which doesn't exist in `cats.effect.utest` causing the following error.

```
object asserts is not a member of package cats.effect.utest
```

## Ammonite Example

```scala
@ import $ivy.`com.codecommit::cats-effect-testing-utest:0.2.0`
@ import cats.effect.utest.IOTestSuite
@ import utest._
@ import cats.effect._

@ object FooTests extends IOTestSuite {
    val tests = Tests {
      test("foo") - {
        assert(true)
      }
    }
  }
cmd4.sc:4: object asserts is not a member of package cats.effect.utest
      assert(true)
            ^
Compilation Failed
```

## Workaround

Suppress `utest` import when importing `cats.effect._`, i.e.
```scala
import cats.effect.{utest => _, _}
```

## Next Steps

Raise a PR for utest to use `_root_.utest` in all macros, I'll try and do that some point this week.

**Comment by djspiewak** [comment]
This definitely isn't *just* a macro issue, for sure. It's a problem that arises due to hierarchical packages. I think we probably should avoid using `utest` (or similar) as a subpackage here.

**Comment by Slakah** [comment]
> Raise a PR for utest to use `_root_.utest` in all macros, I'll try and do that some point this week.

Wouldn't an upstream change to utest fix this as well? Just looking at circe, and that project always prefixes package references with `_root_`, [example from circe](https://github.com/circe/circe/blob/master/modules/literal/src/main/scala/io/circe/literal/JsonLiteralMacros.scala#L19).

**Comment by djspiewak** [comment]
> Wouldn't an upstream change to utest fix this as well? Just looking at circe, and that project always prefixes package references with _root_, example from circe.

Oh it definitely would, but I think that we would still run into this problem in other areas. For example:

```scala
import cats.effect._
import utest.asserts
```

No macro there, but the user just landed themselves in the same situation. I think we should probably just bite the bullet and move everything under the `cats.effect.testing` package or something like that.
