### ISSUE TITLE
was cats-effect-testing-scalatest-scalacheck deprecated?

### ISSUE THREAD

**Issue by pacdaemon** [djspiewak/cats-effect-testing#172]
Hi!, I wonder if cats-effect-testing-scalatest-scalacheck was deprecated, I can see that the README is still referencing it, but there is no `EffectCheckerAsserting` in the default branch.

**Comment by rossabaker** [comment]
Looks like it [perished here](https://github.com/typelevel/cats-effect-testing/commit/39d87af5ac8640315944de37676342fc94db5345#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91).  Sadly, the README doesn't get checked by mdoc.

**Comment by pacdaemon** [comment]
Thank you @rossabaker! I guess I will try to make the old code work by replacing the Effect with the Dispatcher. Or either make use of the `typelevel/scalacheck-effect` library instead.

**Comment by rossabaker** [comment]
Oh, right.  scalacheck-effect should be a good substitute.  See its `PropF.forAllF`.
