### ISSUE TITLE
Scalacheck module?

### ISSUE THREAD

**Issue by dzanot** [djspiewak/cats-effect-testing#185]
The docs reference a `cats-effect-testing-scalatest` module, but it looks like the last version of this published was `0.5.4` and I see no reference to it in the build definition.

Was it deleted?

**Comment by rossabaker** [comment]
There's a scalacheck-effect project now.  See https://github.com/typelevel/cats-effect-testing/issues/172 for more discussion.  I guess we failed to clean that up in the docs.  I'll leave this open until I take care of that.

**Comment by dzanot** [comment]
Rad, thanks team!
