### ISSUE TITLE
Core module publishes as `"org.typelevel" %% "core"`

### ISSUE THREAD

**Issue by armanbilge** [djspiewak/cats-effect-testing#189]
Due to lack of a `name` setting in SBT. Not sure what the best fix is, or defer to the next major version bump?

**Comment by djspiewak** [comment]
😳

Well that's not great. Technically we shouldn't need a major version bump to fix it. It's a frustrating bit of detritus in the sonatype namespace though.

**Comment by rossabaker** [comment]
If it gets fixed, won't we lose eviction between `core` and `cats-effect-core`?  Sounds like a way to play classloader roulette.

**Comment by djspiewak** [comment]
Eviction will still be driven at the top level by the dependencies on the specific test frameworks. The only issue would be if someone is depending directly on core, but no one is doing that because they would have reported that it has the wrong name.

**Comment by armanbilge** [comment]
> but no one is doing that because they would have reported that it has the wrong name.

👋 😆

**Comment by rossabaker** [comment]
Oh, this is cats-effect-testing.  I thought this was cats-effect.  Yeah, that's fine.
