### ISSUE TITLE
How about a new release? 

### ISSUE THREAD

**Issue by kailuowang** [djspiewak/cats-effect-testing#20]
A release with the scalatest module will be really helpful. I will be happy to provide any help if needed.

**Comment by tovbinm** [comment]
Indeed!!

**Comment by djspiewak** [comment]
On it! Expect later this morning

**Comment by djspiewak** [comment]
To be clear, there are a bunch of things I want to work towards cleaning up in the current state of things. Specifically, I'd like to unify the names and capabilities across the testing frameworks. But I have absolutely no problem making a release now and sorting that stuff out later. We are still 0.x after all!

**Comment by djspiewak** [comment]
0.3.0 is out and propagating
